"""add flags table and document_hash

Revision ID: 2d3803bd7996
Revises: 001_create_tables
Create Date: 2026-09-22 10:59:26.916958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3803bd7996'
down_revision: Union[str, None] = '001_create_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('flag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.add_column('contracts', sa.Column('document_hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_contracts_document_hash'), 'contracts', ['document_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_document_hash'), table_name='contracts')
    op.drop_column('contracts', 'document_hash')
    op.drop_table('flags')
    # ### end Alembic commands ###
